version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '5434:5434'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c "npx prisma migrate deploy && yarn start"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres-data:
